unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded from ~/.tmux.conf"

set -g prefix C-space

set -g mouse on
set -g status-position top
set -g base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"

# Vim motions for copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Vim motions for panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# New windows and pane splits should open to the same path as the current window
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# TPM plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"

# Catppuccin theme configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position 'left'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_text ' #W'
set -g @catppuccin_window_current_text ' #W'
set -g @catppuccin_date_time_text " %d-%m %H:%M"

# Run the catppuccin theme script
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

